### ISSUE TITLE
Demo fails to build

### ISSUE THREAD

**Issue by praneethpr** [syncfusion/ej2-vue-samples#18] opened 2020-07-13 19:06 UTC
Unable to get the demo working, please look at the below errors:

OS: MacOS Cantalina 10.15.5
NPM: 6.14.6
NodeJs: 12.13.1

````ppondicherry@hart1874903 syncfusion % npm run build

> ej2-vue-samples@17.4.39 build /Users/ppondicherry/Documents/praneeth/learn/syncfusion
> node --max_old_space_size=4096 node_modules/@vue/cli-service/bin/vue-cli-service.js build


⠙  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
⠦  Building for production...

 ERROR  Failed to compile with 2 errors                                                                                                                   2:01:29 PM

 error  in /Users/ppondicherry/Documents/praneeth/learn/syncfusion/src/App.vue

ERROR in /Users/ppondicherry/Documents/praneeth/learn/syncfusion/src/App.vue
932:72 Parameter 'event' implicitly has an 'any' type.
    930 |                 content: 'Next Sample'
    931 |             });
  > 932 |             select('#right-pane').addEventListener('scroll', function (event) {
        |                                                                        ^
    933 |                 next.close();
    934 |                 previous.close();
    935 |             });

 error  in /Users/ppondicherry/Documents/praneeth/learn/syncfusion/src/index.ts

ERROR in /Users/ppondicherry/Documents/praneeth/learn/syncfusion/src/index.ts
583:72 Parameter 'event' implicitly has an 'any' type.
    581 |                 content: 'Next Sample'
    582 |             });
  > 583 |             select('#right-pane').addEventListener('scroll', function (event) {
        |                                                                        ^
    584 |                 next.close();
    585 |                 previous.close();
    586 |             });

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ej2-vue-samples@17.4.39 build: `node --max_old_space_size=4096 node_modules/@vue/cli-service/bin/vue-cli-service.js build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ej2-vue-samples@17.4.39 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ppondicherry/.npm/_logs/2020-07-13T19_01_30_629Z-debug.log
````

**Comment by jesusarockias** [comment] 2020-07-14 16:59
@praneethpr We have fixed this build error and you can find the details from the below pull request.
https://github.com/syncfusion/ej2-vue-samples/pull/19/

Also, we request you check our online demos and documentation for quick reference. 

**Demo**: https://ej2.syncfusion.com/vue/demos/

**Documentation**: https://ej2.syncfusion.com/vue/documentation/introduction/

**Comment by gsumankumar** [comment] 2022-02-09 10:01
We have closing this issue now, since there's no recent activities. if the issue is still persist, please feel free to reopen it.

**Closed as completed by gsumankumar** 2022-02-09 10:01 UTC
